version: "3.9"

services:
  backend-5000:
    image: buhyun459/ktb-backend:latest   # <-- 빌드한 이미지 이름
    container_name: backend-5000
    network_mode: host
    env_file:
      - .env
    environment:
      - PORT=5000                          # Node.js 내부 포트
    command: ["node", "server.js"]         # 서버 실행 명령
    restart: always

  backend-5001:
    image: buhyun459/ktb-backend:latest
    container_name: backend-5001
    network_mode: host
    env_file:
      - .env
    environment:
      - PORT=5001
    command: ["node", "server.js"]
    restart: always

  # backend-5002:
  #   image: buhyun459/ktb-backend:latest
  #   container_name: backend-5002
  #   network_mode: host
  #   env_file:
  #     - .env
  #   environment:
  #     - PORT=5002
  #   command: ["node", "server.js"]
  #   restart: always

  # backend-5003:
  #   image: buhyun459/ktb-backend:latest
  #   container_name: backend-5003
  #   network_mode: host
  #   env_file:
  #     - .env
  #   environment:
  #     - PORT=5003
  #   command: ["node", "server.js"]
  #   restart: always

  # backend-5004:
  #   image: buhyun459/ktb-backend:latest
  #   container_name: backend-5004
  #   network_mode: host
  #   env_file:
  #     - .env
  #   environment:
  #     - PORT=5004
  #   command: ["node", "server.js"]
  #   restart: always